[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.6"
hooks = [
    { id = "ruff-check" },
    { id = "ruff-format" },
]

[[repos]]
repo = "local"
hooks = [
    {
        id = "ty-check",
        name = "ty",
        entry = "uvx ty check",
        language = "system",
        types = ["python"],
    },
]
